POST http://localhost:3001/api/trackers
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzY2Q1MGRmMjA5MDUyNjE2ZTUyZjFkOCIsInVzZXJuYW1lIjoiaGFkaGFkIiwiaWF0IjoxNjc0NDA0OTEzLCJleHAiOjE2NzQ0MDUyMTN9.AwWjTbFqcIATEUw7hUYQjt2I5sec-qXTF-6QokI9xkA

{
  "productId": "110546385273",
  "productName": "Portable Monitor,ARZOPA 15.6“ 1080P FHD USB-C Laptop Monitor HDMI Gaming Monitor",
  "productLink": "https://cgi.sandbox.ebay.com/Portable-Monitor-ARZOPA-15-6-1080P-FHD-USB-C-Laptop-Monitor-HDMI-Gaming-Monitor-/110546385273",
  "productImage": "https://i.ebayimg.sandbox.ebay.com/images/g/X3wAAOSwyGxiGIAf/s-l140.jpg",
  "productPrice": "139.99",
  "productCurrency": "USD",
  "productStore": "ebay",
  "desiredPrice": "99.99"
}