POST http://localhost:3001/api/trackers
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzY2Q1MGRmMjA5MDUyNjE2ZTUyZjFkOCIsInVzZXJuYW1lIjoiaGFkaGFkIiwiaWF0IjoxNjc0NDA0OTEzLCJleHAiOjE2NzQ0MDUyMTN9.AwWjTbFqcIATEUw7hUYQjt2I5sec-qXTF-6QokI9xkA

{
  "productId": "110546467601",
  "productName": "AVS 24445 Bugflector II Stone/Bug Deflector For 01-04 Fits Nissan Frontier",
  "productLink": "https://cgi.sandbox.ebay.com/AVS-24445-Bugflector-II-Stone-Bug-Deflector-01-04-Fits-Nissan-Frontier-/110546467601",
  "productImage": "",
  "productPrice": "80.33",
  "productCurrency": "USD",
  "productStore": "ebay",
  "desiredPrice": "50.33"
}