GET http://localhost:3001/api/trackers
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzY2Q1MGRmMjA5MDUyNjE2ZTUyZjFkOCIsInVzZXJuYW1lIjoiaGFkaGFkIiwiaWF0IjoxNjc0NDA1NTU0LCJleHAiOjE2NzQ0MDU4NTR9.M7NyhrN7-TLzyljQdca4vAm51n-amjIXqfxl-kuSP2A