PUT http://localhost:3001/api/trackers/63cd64645b3fca0d8bab8cd2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzY2Q1MGRmMjA5MDUyNjE2ZTUyZjFkOCIsInVzZXJuYW1lIjoiaGFkaGFkIiwiaWF0IjoxNjc0NDA1NzU0LCJleHAiOjE2NzQ0MDYwNTR9.Wz7jilXuUlklTG3C-cuDTTee5ecl9MyPLhD2p-Bd4xA

{
  "desiredPrice": "62.33"
}